export const propertiesData = {
  items: [
    {
      id: 2,
      created_at: '2021-08-17T19:31:34.000000Z',
      updated_at: '2021-08-17T19:31:34.000000Z',
      property_type1: 'personal',
      property_type2: 'private',
      full_address: 'USA New York',
      country: 'USA',
      state: 'NY',
      city: 'New York',
      postal_code: '54664',
      latitude: 125.23,
      longitude: 69.25,
      maximum_guests: 6,
      number_of_rooms_bath: 3,
      number_of_rooms: 2,
      number_of_beds: 4,
      number_of_open_concept_rooms: 3,
      customer_expectations: ['nearby_noise_potential', 'must_climb_stairs'],
      securities: ['smoke_detector', 'first_aid_kit'],
      amenities: ['access_to_a_garage'],
      rules: ['minimum_age_to_rent'],
      regulations: ['suitable_for_children', 'accepted_animals'],
      cancellation_policy_type: 'flexible',
      tax_registration_number: '112121',
      taxes: [
        {
          name: 'tax1',
          value: 1111,
        },
        {
          name: 'tax2',
          value: 220,
        },
      ],
      is_active: false,
      is_published: false,
      user_id: 5,
      rooms: [
        {
          id: 3,
          created_at: '2021-08-17T19:31:34.000000Z',
          updated_at: '2021-08-17T19:31:34.000000Z',
          name: 'room',
          sleeping_types: null,
        },
        {
          id: 4,
          created_at: '2021-08-17T19:31:34.000000Z',
          updated_at: '2021-08-17T19:31:34.000000Z',
          name: 'room1',
          sleeping_types: [
            {
              value: 1,
              category: 'simple',
            },
          ],
        },
      ],
      photos: [],
      basic_pricing: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        is_smart: true,
        currency: 'USD',
        base_rate: 1,
        weekend_rate: 1.1,
        weekly_rate: 1.6,
        monthly_rate: 1.2,
      },
      rental_parameter: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        booking_preferences: 'reservation_request',
        arriving_time: '17:00',
        departure_time: '18:00',
        min_nights_to_rent: 1,
        max_nights_to_rent: 2,
        advanced_booking_options: {
          max_length_of_stays: {
            Mon: 1,
            Tue: 2,
          },
          arrival_departure_days: ['Mon', 'Tue'],
          minimum_delay_before_arrival: 1,
          allow_same_day_departure_or_arrival: true,
          months_in_advance_receive_reservations: 2,
        },
      },
      basic_fee: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        cleaning_fee: 10.2,
        security_deposit: 11.35,
        above_number_of_guests: 6,
        fee_per_additional_guest: 0.5,
        other_charges: [
          {
            optional: false,
            service_name: 'service name',
            service_price: 11.34,
            how_is_it_charged: 'how_is_it_charged',
          },
          {
            optional: false,
            service_name: 'service name',
            service_price: 11.34,
            how_is_it_charged: 'how_is_it_charged',
          },
        ],
      },
      guest_reception: null,
      calendars: [],
      ical_feeds: [],
      user: {
        id: 5,
        name: 'user user',
        email: 'simon.andrei879@gmail.com',
        email_verified_at: null,
        role: 2,
        status: 1,
        picture: null,
        birthdate: null,
        language: null,
        created_at: '2021-08-18T19:22:41.000000Z',
        updated_at: '2021-08-18T19:22:41.000000Z',
      },
    },
    {
      id: 2,
      created_at: '2021-08-17T19:31:34.000000Z',
      updated_at: '2021-08-17T19:31:34.000000Z',
      property_type1: 'personal',
      property_type2: 'private',
      full_address: 'USA New York',
      country: 'USA',
      state: 'NY',
      city: 'New York',
      postal_code: '54664',
      latitude: 125.23,
      longitude: 69.25,
      maximum_guests: 6,
      number_of_rooms_bath: 3,
      number_of_rooms: 2,
      number_of_beds: 4,
      number_of_open_concept_rooms: 3,
      customer_expectations: ['nearby_noise_potential', 'must_climb_stairs'],
      securities: ['smoke_detector', 'first_aid_kit'],
      amenities: ['access_to_a_garage'],
      rules: ['minimum_age_to_rent'],
      regulations: ['suitable_for_children', 'accepted_animals'],
      cancellation_policy_type: 'flexible',
      tax_registration_number: '112121',
      taxes: [
        {
          name: 'tax1',
          value: 1111,
        },
        {
          name: 'tax2',
          value: 220,
        },
      ],
      is_active: false,
      is_published: false,
      user_id: 5,
      rooms: [
        {
          id: 3,
          created_at: '2021-08-17T19:31:34.000000Z',
          updated_at: '2021-08-17T19:31:34.000000Z',
          name: 'room',
          sleeping_types: null,
        },
        {
          id: 4,
          created_at: '2021-08-17T19:31:34.000000Z',
          updated_at: '2021-08-17T19:31:34.000000Z',
          name: 'room1',
          sleeping_types: [
            {
              value: 1,
              category: 'simple',
            },
          ],
        },
      ],
      photos: [],
      basic_pricing: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        is_smart: true,
        currency: 'USD',
        base_rate: 1,
        weekend_rate: 1.1,
        weekly_rate: 1.6,
        monthly_rate: 1.2,
      },
      rental_parameter: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        booking_preferences: 'reservation_request',
        arriving_time: '17:00',
        departure_time: '18:00',
        min_nights_to_rent: 1,
        max_nights_to_rent: 2,
        advanced_booking_options: {
          max_length_of_stays: {
            Mon: 1,
            Tue: 2,
          },
          arrival_departure_days: ['Mon', 'Tue'],
          minimum_delay_before_arrival: 1,
          allow_same_day_departure_or_arrival: true,
          months_in_advance_receive_reservations: 2,
        },
      },
      basic_fee: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        cleaning_fee: 10.2,
        security_deposit: 11.35,
        above_number_of_guests: 6,
        fee_per_additional_guest: 0.5,
        other_charges: [
          {
            optional: false,
            service_name: 'service name',
            service_price: 11.34,
            how_is_it_charged: 'how_is_it_charged',
          },
          {
            optional: false,
            service_name: 'service name',
            service_price: 11.34,
            how_is_it_charged: 'how_is_it_charged',
          },
        ],
      },
      guest_reception: null,
      calendars: [],
      ical_feeds: [],
      user: {
        id: 5,
        name: 'user user',
        email: 'simon.andrei879@gmail.com',
        email_verified_at: null,
        role: 2,
        status: 1,
        picture: null,
        birthdate: null,
        language: null,
        created_at: '2021-08-18T19:22:41.000000Z',
        updated_at: '2021-08-18T19:22:41.000000Z',
      },
    },
    {
      id: 2,
      created_at: '2021-08-17T19:31:34.000000Z',
      updated_at: '2021-08-17T19:31:34.000000Z',
      property_type1: 'personal',
      property_type2: 'private',
      full_address: 'USA New York',
      country: 'USA',
      state: 'NY',
      city: 'New York',
      postal_code: '54664',
      latitude: 125.23,
      longitude: 69.25,
      maximum_guests: 6,
      number_of_rooms_bath: 3,
      number_of_rooms: 2,
      number_of_beds: 4,
      number_of_open_concept_rooms: 3,
      customer_expectations: ['nearby_noise_potential', 'must_climb_stairs'],
      securities: ['smoke_detector', 'first_aid_kit'],
      amenities: ['access_to_a_garage'],
      rules: ['minimum_age_to_rent'],
      regulations: ['suitable_for_children', 'accepted_animals'],
      cancellation_policy_type: 'flexible',
      tax_registration_number: '112121',
      taxes: [
        {
          name: 'tax1',
          value: 1111,
        },
        {
          name: 'tax2',
          value: 220,
        },
      ],
      is_active: false,
      is_published: false,
      user_id: 5,
      rooms: [
        {
          id: 3,
          created_at: '2021-08-17T19:31:34.000000Z',
          updated_at: '2021-08-17T19:31:34.000000Z',
          name: 'room',
          sleeping_types: null,
        },
        {
          id: 4,
          created_at: '2021-08-17T19:31:34.000000Z',
          updated_at: '2021-08-17T19:31:34.000000Z',
          name: 'room1',
          sleeping_types: [
            {
              value: 1,
              category: 'simple',
            },
          ],
        },
      ],
      photos: [],
      basic_pricing: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        is_smart: true,
        currency: 'USD',
        base_rate: 1,
        weekend_rate: 1.1,
        weekly_rate: 1.6,
        monthly_rate: 1.2,
      },
      rental_parameter: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        booking_preferences: 'reservation_request',
        arriving_time: '17:00',
        departure_time: '18:00',
        min_nights_to_rent: 1,
        max_nights_to_rent: 2,
        advanced_booking_options: {
          max_length_of_stays: {
            Mon: 1,
            Tue: 2,
          },
          arrival_departure_days: ['Mon', 'Tue'],
          minimum_delay_before_arrival: 1,
          allow_same_day_departure_or_arrival: true,
          months_in_advance_receive_reservations: 2,
        },
      },
      basic_fee: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        cleaning_fee: 10.2,
        security_deposit: 11.35,
        above_number_of_guests: 6,
        fee_per_additional_guest: 0.5,
        other_charges: [
          {
            optional: false,
            service_name: 'service name',
            service_price: 11.34,
            how_is_it_charged: 'how_is_it_charged',
          },
          {
            optional: false,
            service_name: 'service name',
            service_price: 11.34,
            how_is_it_charged: 'how_is_it_charged',
          },
        ],
      },
      guest_reception: null,
      calendars: [],
      ical_feeds: [],
      user: {
        id: 5,
        name: 'user user',
        email: 'simon.andrei879@gmail.com',
        email_verified_at: null,
        role: 2,
        status: 1,
        picture: null,
        birthdate: null,
        language: null,
        created_at: '2021-08-18T19:22:41.000000Z',
        updated_at: '2021-08-18T19:22:41.000000Z',
      },
    },
    {
      id: 2,
      created_at: '2021-08-17T19:31:34.000000Z',
      updated_at: '2021-08-17T19:31:34.000000Z',
      property_type1: 'personal',
      property_type2: 'private',
      full_address: 'USA New York',
      country: 'USA',
      state: 'NY',
      city: 'New York',
      postal_code: '54664',
      latitude: 125.23,
      longitude: 69.25,
      maximum_guests: 6,
      number_of_rooms_bath: 3,
      number_of_rooms: 2,
      number_of_beds: 4,
      number_of_open_concept_rooms: 3,
      customer_expectations: ['nearby_noise_potential', 'must_climb_stairs'],
      securities: ['smoke_detector', 'first_aid_kit'],
      amenities: ['access_to_a_garage'],
      rules: ['minimum_age_to_rent'],
      regulations: ['suitable_for_children', 'accepted_animals'],
      cancellation_policy_type: 'flexible',
      tax_registration_number: '112121',
      taxes: [
        {
          name: 'tax1',
          value: 1111,
        },
        {
          name: 'tax2',
          value: 220,
        },
      ],
      is_active: false,
      is_published: false,
      user_id: 5,
      rooms: [
        {
          id: 3,
          created_at: '2021-08-17T19:31:34.000000Z',
          updated_at: '2021-08-17T19:31:34.000000Z',
          name: 'room',
          sleeping_types: null,
        },
        {
          id: 4,
          created_at: '2021-08-17T19:31:34.000000Z',
          updated_at: '2021-08-17T19:31:34.000000Z',
          name: 'room1',
          sleeping_types: [
            {
              value: 1,
              category: 'simple',
            },
          ],
        },
      ],
      photos: [],
      basic_pricing: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        is_smart: true,
        currency: 'USD',
        base_rate: 1,
        weekend_rate: 1.1,
        weekly_rate: 1.6,
        monthly_rate: 1.2,
      },
      rental_parameter: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        booking_preferences: 'reservation_request',
        arriving_time: '17:00',
        departure_time: '18:00',
        min_nights_to_rent: 1,
        max_nights_to_rent: 2,
        advanced_booking_options: {
          max_length_of_stays: {
            Mon: 1,
            Tue: 2,
          },
          arrival_departure_days: ['Mon', 'Tue'],
          minimum_delay_before_arrival: 1,
          allow_same_day_departure_or_arrival: true,
          months_in_advance_receive_reservations: 2,
        },
      },
      basic_fee: {
        id: 2,
        created_at: '2021-08-17T19:31:34.000000Z',
        updated_at: '2021-08-17T19:31:34.000000Z',
        cleaning_fee: 10.2,
        security_deposit: 11.35,
        above_number_of_guests: 6,
        fee_per_additional_guest: 0.5,
        other_charges: [
          {
            optional: false,
            service_name: 'service name',
            service_price: 11.34,
            how_is_it_charged: 'how_is_it_charged',
          },
          {
            optional: false,
            service_name: 'service name',
            service_price: 11.34,
            how_is_it_charged: 'how_is_it_charged',
          },
        ],
      },
      guest_reception: null,
      calendars: [],
      ical_feeds: [],
      user: {
        id: 5,
        name: 'user user',
        email: 'simon.andrei879@gmail.com',
        email_verified_at: null,
        role: 2,
        status: 1,
        picture: null,
        birthdate: null,
        language: null,
        created_at: '2021-08-18T19:22:41.000000Z',
        updated_at: '2021-08-18T19:22:41.000000Z',
      },
    },
  ],
  total: 4,
  page: 2,
  limit: 1,
}
